[2020-05-11 00:01:49,944] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-11 00:04:03,350] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py changed, reloading.
[2020-05-11 00:04:05,443] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-11 00:04:28,608] [views.py:29] [views:request_img_predict] [INFO]- request_img_predict
[2020-05-11 00:04:28,902] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /request_img_predict/
Traceback (most recent call last):
  File "e:\Anaconda\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "e:\Anaconda\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "e:\Anaconda\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\论文\代码\DjangoProject\djangoDemo\app_demo\views.py", line 31, in request_img_predict
    return JsonResponse(query_img_predict(request))
  File "E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py", line 15, in query_img_predict
    img_name = data.get('img_name',DEFAULT_IMG_NAME)
TypeError: 'QueryDict' object is not callable
[2020-05-11 00:04:28,906] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /request_img_predict/ HTTP/1.1" 500 225948
[2020-05-11 00:07:17,600] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py changed, reloading.
[2020-05-11 00:07:19,602] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-11 00:07:41,668] [views.py:29] [views:request_img_predict] [INFO]- request_img_predict
[2020-05-11 00:07:42,105] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /request_img_predict/ HTTP/1.1" 200 159
[2020-05-11 00:09:33,553] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py changed, reloading.
[2020-05-11 00:09:36,364] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-11 00:09:51,607] [views.py:29] [views:request_img_predict] [INFO]- request_img_predict
[2020-05-11 00:09:51,757] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /request_img_predict/
Traceback (most recent call last):
  File "e:\Anaconda\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "e:\Anaconda\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "e:\Anaconda\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\论文\代码\DjangoProject\djangoDemo\app_demo\views.py", line 31, in request_img_predict
    return JsonResponse(query_img_predict(request))
  File "E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py", line 16, in query_img_predict
    img_name = data.get('img_name',defalut=DEFAULT_IMG_NAME)
TypeError: get() got an unexpected keyword argument 'defalut'
[2020-05-11 00:09:51,766] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /request_img_predict/ HTTP/1.1" 500 226044
[2020-05-11 00:10:10,877] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py changed, reloading.
[2020-05-11 00:10:13,262] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-11 00:10:29,655] [views.py:29] [views:request_img_predict] [INFO]- request_img_predict
[2020-05-11 00:10:30,010] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /request_img_predict/ HTTP/1.1" 200 162
[2020-05-11 00:10:56,458] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py changed, reloading.
[2020-05-11 00:10:58,838] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-11 00:11:25,951] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py changed, reloading.
[2020-05-11 00:11:28,787] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-05-11 00:14:40,960] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- E:\论文\代码\DjangoProject\djangoDemo\app_demo\request_utils\request_response.py changed, reloading.
[2020-05-11 00:14:44,792] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
